### ISSUE TITLE
cannot use _Ctype_size_t(quality)... 

### ISSUE THREAD

**Issue by robertmeta** [quirkey/magick#5]
src/github.com/quirkey/magick/magick.go:330: cannot use _Ctype_size_t(quality) (type C.size_t) as type C.ulong in assignment
- CENTOS 6.4 with ImageMagick-devel (ImageMagick-devel-6.5.4.7-6.el6_2.x86_64) installed.  
- go version go1.2 linux/amd64
- gcc version 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC)

If I dumbly swap it to a ulong, it compiles but doesn't pass tests.

**Comment by quirkey** [comment]
We're using ImageMagick 6.7.6-9 (2012-05-14) on Centos 6.4 and it compiles and runs cleanly.

**Comment by pearkes** [comment]
Ran into this on [Heroku](http://heroku.com) as they use `ImageMagick 6.5.7-8 2012-08-17 Q16`.

Confirmed that it works on newer versions, just thought I would note it for future users.
