### ISSUE TITLE
memory

### ISSUE THREAD

**Issue by gravityblast** [quirkey/magick#7]
I have a simple web app that generates thumbnails with magick. I noticed that if each request generates a different image, the memory is continuously increasing.
here an example:

``` go
package main

import (
    "fmt"
    "github.com/quirkey/magick"
    "log"
    "net/http"
)

var i = 1

func handler(w http.ResponseWriter, r *http.Request) {
    // size := 2000 // no problem with fixed size
    size := 200 + i
    i += 1

    image, _ := magick.NewFromFile("test.jpg")
    defer image.Destroy()
    image.Resize(fmt.Sprintf("%dx%d", size, size))
    image.ToFile("output.jpg")
    fmt.Fprint(w, "OK")
    println(i)
}

func main() {
    http.HandleFunc("/", handler)
    log.Fatal(http.ListenAndServe(":7000", nil))
}
```

is there anything I'm missing or doing wrong?

**Comment by quirkey** [comment]
We've had different results with memory usage of Magick as well. There are a couple different factors at play: 1) Different versions of ImageMagick produce different results in terms of memory usage. We've seen very high usage on versions on OS X compared to Linux (centos). 2) Go and ImageMagick each have their own stack, ImageMagick will reuse any stack that it allocates but will not free this back to the OS. Go will continually grow its stack, but will eventually (more quickly in Go 1.2) free the memory back to the stack. 

Having said that, we're running this in production with a very high volume of requests and its going well. If there is a high level of concurrency, IM will have to grow its stack to accommodate but we've found (at least in our usage) that this reaches an upper bound and stays there.

We want to improve the speed and memory usage of this, though, so we're constantly looking for ways to use CGO and IM better. IM 7 seems to have better memory performance but its not yet widely available.

**Comment by sdbaiguanghe** [comment]
I have the same question but only in processing  gif，the memory seems  increasing endlessly
    image, _ := magick.NewFromFile("test.gif")
    defer image.Destroy()
    image.Resize(fmt.Sprintf("%dx%d", gif, gif))
    image.ToFile("test_first_frame.gif")

**Comment by sdbaiguanghe** [comment]
I have the same question but only process  gif，the memory seems  increasing endlessly
``` image, _ := magick.NewFromFile("test.gif")
    defer image.Destroy()
    image.Resize(fmt.Sprintf("%dx%d", gif, gif))
    image.ToFile("test_first_frame.gif")```

**Comment by sdbaiguanghe** [comment]
I have the same question but only process  gif，the memory seems  increasing endlessly

```
      image, _ := magick.NewFromFile("test.gif")
      defer image.Destroy()
      image.Resize(fmt.Sprintf("%dx%d", gif, gif))
      image.ToFile("test_first_frame.gif")
```

**Comment by quirkey** [comment]
@sdbaiguanghe Is that run inside of a function? If not, defer'd Destroy() might never be called. Also, go will not release memory back to the operating system immediately so if you're allocating memory in a tight loop RSS will grow quickly. It's worth looking at go's MemStats and MemProfile to see if its able to release memory or if the heap continues to grow.
